### ISSUE TITLE
KZLA: Merge LS airspace classes by type

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#104]
![image](https://user-images.githubusercontent.com/41238983/121558673-dd26d180-c9e3-11eb-807a-b66089d5bf9d.png)

Low Sector airspaces should be consolidated into the type of airspace. For example: 

- Class D
- Class C
- Class B

This will be easier to toggle for ATC.

**Comment by MobiasTagill** [comment]
need any help?
