### ISSUE TITLE
KZDV: CLASH3 arrival is missing runway transitions

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#115]
![image](https://user-images.githubusercontent.com/41238983/121994483-5c652e00-cd73-11eb-86b1-8d12511dbb43.png)

![image](https://user-images.githubusercontent.com/41238983/121994502-64bd6900-cd73-11eb-98fc-ef146969d8db.png)

Link to chart (FAA): https://aeronav.faa.gov/d-tpp/2105/09077CLASH_C.PDF

All fixes are present but lines are not drawn.

Reported by Rick K.

**Comment by wessupermare** [comment]
Feature, not a bug. If you switch runways and re-show the procedure, it'll only show you the portion of the arrival applicable to your runway. If the runway change isn't working for you, let me know and I'll take another look.
