### ISSUE TITLE
KZNY: KEWR airport layout outdated

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#118]
EWR needs taxiway labels updates, as well as some ramp/building graphics removed.

New taxiway A9
New LINDY ramp
New AREA 2 ramp
Western ramps removed
New taxiway A11

![image](https://user-images.githubusercontent.com/41238983/122160421-e4b00580-ce3d-11eb-89e0-3ba5437ba32c.png)

![image](https://user-images.githubusercontent.com/41238983/122160209-83883200-ce3d-11eb-940f-9715a5c5ca3c.png)

Reference:
https://aeronav.faa.gov/d-tpp/2105/00285AD.PDF

**Comment by JordanKirkby** [comment]
Beginner Friendly?

**Comment by aldobenitez** [comment]
> Beginner Friendly?

Not currently, would require to redo that part of the ramp, and remove some other ramps and buildings in that corner. We found out there is a whole new terminal building being constructed actually.

**Comment by JordanKirkby** [comment]
Removed tag.

Maybe it would be best to update once the new terminal is live.

Simulators wont be updated until that time too.  Unless MFS has updated?
