### ISSUE TITLE
Fix Filler - Canada

### ISSUE THREAD

**Issue by JordanKirkby** [ivao-xa/sectorfiles#152]
Hi Guys, don't see why we cant use the navdata to get the fix filler to work for Canada.

Wes, can you have a look into it?

Thanks buddy.

**Comment by wessupermare** [comment]
Can anyone find a website or (even better) an API that has fixes for Canada or (better still) all of XA? Currently we use AirNav, but that's mostly just US only.

**Comment by JordanKirkby** [comment]
You cant scrape it from Navigraph data?

**Comment by JordanKirkby** [comment]
Not sure, but this site seems to have A LOT 

https://www.globalair.com/airport/airspacefix.aspx

**Comment by wessupermare** [comment]
> https://www.globalair.com/airport/airspacefix.aspx

![image](https://user-images.githubusercontent.com/9663827/125118992-511cce00-e0a5-11eb-9dd1-c483da5e42ef.png)

Still looks like it's probably just FAA data again; good try though!

**Comment by aldobenitez** [comment]
What if we generate Canadian fixes file via IAB? 
![image](https://user-images.githubusercontent.com/41238983/125121351-cc8c7880-e0c1-11eb-9b6b-e5d29432d58e.png)

**Comment by JordanKirkby** [comment]
Where is the Vertex File?

**Comment by wessupermare** [comment]
![image](https://user-images.githubusercontent.com/9663827/125150381-52291c00-e0f4-11eb-83af-abb088d7a0c5.png)

FixFiller now supports about 70% of Canadian fixes. The rest still need to be done by hand.
[FixFiller.zip](https://github.com/ivao-xa/sectorfiles/files/6794594/FixFiller.zip)

**Comment by wessupermare** [comment]
Edit: VOR issues. New version:
[FixFiller.zip](https://github.com/ivao-xa/sectorfiles/files/6795531/FixFiller.zip)
