### ISSUE TITLE
KZOA: SFO TWR frequency incorrect

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#156]
**ARTCC/FIR:**

KZOA

**Description:**

Incorrect frequency for KSFO TWR.

**Comment by JordanKirkby** [comment]
Looks correct to me?

![image](https://user-images.githubusercontent.com/85253992/125269392-a5f35b00-e2d6-11eb-9cfa-a8d170471d81.png)
![image](https://user-images.githubusercontent.com/85253992/125269431-b0155980-e2d6-11eb-9243-f9df7ef1f3fd.png)

**Comment by aldobenitez** [comment]
Reviewed. Frequency is correct. 
![image](https://user-images.githubusercontent.com/41238983/125485541-0d03aabb-9a9b-4270-ad0c-fab3f71adbfa.png)
