### ISSUE TITLE
KLAX TBIT gates at C10

### ISSUE THREAD

**Issue by frankiePRG** [ivao-xa/sectorfiles#158]
Missing gate 159 at TB! :D Gates 155 and 157 are now misplaced -159 should be where 157 is right now. Please see the screenshot attached.

Thank you! :)

![Výstřižek](https://user-images.githubusercontent.com/59516819/125176527-79571a80-e1d4-11eb-9cbf-8a615ca9cf6f.PNG)

**Comment by frankiePRG** [comment]
ALSO!! Please, we have two gates 48A at terminal 4 now. Gates should be 40 - 42A - 42B - 46A - 46B - 46C - 48A - 48B. Terminal 5 seeing a similar issue. Thank you :)

**Comment by aldobenitez** [comment]
gates fixed

![image](https://user-images.githubusercontent.com/41238983/128642309-9839fd4e-1e72-4129-9203-49adf7497ff9.png)
