### ISSUE TITLE
Adding and editing taxiway labels for Palm Springs 

### ISSUE THREAD

**Issue by thediamondguest** [ivao-xa/sectorfiles#166]
**Description:**

After comparing the layout of PSP in Aurora with the FAA chart, there are some taxiways that need to be labeled, and others that need to be re-labeled. Additionally, Atlantic Aviation, IIRC has a one way traffic system in which traffic enters the FBO ramp via A and exits via B. 

**ARTCC/FIR:**

KZLA (Los Angeles Center)
![Updated PSP diagram](https://user-images.githubusercontent.com/87151916/125393966-be5a8880-e35d-11eb-96a7-9ab698d98216.png)
[FlightAware_PSP_APD_AIRPORT DIAGRAM.PDF](https://github.com/ivao-xa/sectorfiles/files/6806043/FlightAware_PSP_APD_AIRPORT.DIAGRAM.PDF)

**Comment by aldobenitez** [comment]
![image](https://user-images.githubusercontent.com/41238983/128642287-e86ab801-3bdb-4750-85c2-a5fd15435403.png)
PSP updates have been implemented
