### ISSUE TITLE
Long Beach Updates

### ISSUE THREAD

**Issue by thediamondguest** [ivao-xa/sectorfiles#178]
**Description:**

Since there are no labels for taxiways, aprons, terminals and parking, I took the liberty of making some updates. 

A few key notes:

1. 26L/8R is shortened, terminating at the junction of F1 and D.
2. Taxiway C is separated from the passenger terminal apron by 2 taxiways, C2 and C1. 
3. The large triangle area is not an entire apron area, bounded by B on the West, D on the East (parallels 30/12), J on the South and G to the North. 
4. The intersection of D4, L4 and 30/12 has been moved to the North slightly, and is angled to provide a 90 degree intersection with the runway. 
5. There are 3 helipads in the area bounded by 30/12 to the West, K to the North, G to the South, and C to the East. 

**ARTCC/FIR:**

KZLA (Los Angeles Center)
![LGB Updates](https://user-images.githubusercontent.com/87151916/126055149-fc535b28-5425-4325-b88e-a370901e1326.png)
https://longbeach.gov/lgb/resources/airfield-diagram/

**Comment by aldobenitez** [comment]
LGB updates have been implemented
