### ISSUE TITLE
KZHU procedures updates

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#191]
**Description:**
Needs generated terminal procedures. Please attached zip to this issue request if possible.

**ARTCC/FIR:**
KZHU

**Comment by wessupermare** [comment]
[fixes.fix.txt](https://github.com/ivao-xa/sectorfiles/files/6957853/fixes.fix.txt)
[procedures.zip](https://github.com/ivao-xa/sectorfiles/files/6957854/procedures.zip)

Delete the `.txt` from the end of the fix file. That's just to stop GitHub from complaining. 🙂
