### ISSUE TITLE
CZYZ: Airport CYHM green backround

### ISSUE THREAD

**Issue by LenEdwinW** [ivao-xa/sectorfiles#209]
**ARTCC/FIR:**
CZYZ

**Description:**
The airport CYHM has a green backround. All other airports in this sectorfile do not have this.

**Screenshots/Images:**
![image](https://user-images.githubusercontent.com/82312020/132128934-cddd826e-e162-488e-bdfd-0e8ad1933401.png)

**Comment by JordanKirkby** [comment]
I will remove the BG color.

NavCan uses it in certain situations, so I thought I would try it out.
