### ISSUE TITLE
CZYZ: Airport CYTS missing Taxiway labels

### ISSUE THREAD

**Issue by LenEdwinW** [ivao-xa/sectorfiles#213]
**Is your feature request related to a problem? Please describe.**
On the Airport CYTS there are no Taxiway descriptions. (See screenshot) (Taxiway labels are enabled in Aurora, as I can see all the other labels on other airports. 

**Sector**
CZYZ Aurora
![image](https://user-images.githubusercontent.com/82312020/132254395-4df82b39-c4ff-46f2-8410-97785352ae97.png)

**Comment by JordanKirkby** [comment]
![image](https://user-images.githubusercontent.com/85253992/133661346-9e5e4fbd-e89f-4f80-88ca-076d6e5ed92f.png)
