### ISSUE TITLE
KZLA - SoCal TEC Routes

### ISSUE THREAD

**Issue by wessupermare** [ivao-xa/sectorfiles#214]
**Is your feature request related to a problem? Please describe.**
SoCal has an expansive system of over 3500 TEC routes which pilots are encouraged to file. These routes won't show up in Aurora if the pilot files them, so excessive external lookups are required.

**Sector**
KZLA

**Describe the solution you'd like**
All TEC routes added to the sectorfile.

**Comment by aldobenitez** [comment]
@wessupermare What if we add the TEC routes as Low airways? I believe aurora would then be able to display the tec route if it's in the flightplan?

**Comment by wessupermare** [comment]
I'm thinking making them a single SIDs/STARs file and referencing it from the KZLA isc. That way it could be used in the route box as well from the ground and could include altitude restrictions.
