### ISSUE TITLE
ZAB procedures in sector file needs to be updated

### ISSUE THREAD

**Issue by AlexSkeleton12** [ivao-xa/sectorfiles#263]
**ARTCC/FIR:**
KZAB

**Description:**
Missing procedures, misplaced procedures, and old procedures in sector file that need to be replaced (a lot of airports).

**Screenshots/Images:**
One example:
![Capture](https://user-images.githubusercontent.com/50224102/155850464-0666e9f1-4a0c-427b-9828-425a36c085f0.PNG)

**Comment by aldobenitez** [comment]
@AlexSkeleton12 You probably have an older version. I can tell because new sectorfiles don't use (RNAV) tag anymore :D

Here is KABQ GRZZZ SID in the current version:

![image](https://user-images.githubusercontent.com/41238983/156107791-61534848-485c-42a2-aa23-81007af028e7.png)
