### ISSUE TITLE
CZYZ: Add Sids/Stars CYHM Hamilton International Airport. 

### ISSUE THREAD

**Issue by JordanKirkby** [ivao-xa/sectorfiles#37]
**Old information**
What is out of date? Yes,none added currently. 

**Sector**
Which sectorfile is the request for?
CZYZ

**Comment by wessupermare** [comment]
![image](https://user-images.githubusercontent.com/9663827/120840913-bc352b00-c562-11eb-87fe-e970132e17c7.png)

Only 2 SIDs and 16 STAR/runway combinations available here. Validate these for me and let me know if you need anything fixed.

https://1drv.ms/u/s!AmrBW1nfZNbRz_x5dhGV01gaEBdXKw?e=kaLbOD
