### ISSUE TITLE
KZKC: SID/STARs update

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#38]
**Old information**
SID/STAR

**Sector**
KZKC

**Additional context**
Requested for: KTUL KSPI KSGF KICT KSTL KMCI

**Comment by wessupermare** [comment]
No procedures available for KSPI, KSGF, or KICT. Approaches available only for KMCI.

![image](https://user-images.githubusercontent.com/9663827/120840585-5b0d5780-c562-11eb-8587-0d2748a6935c.png)

**Comment by wessupermare** [comment]
Whoops! Turns out the tool was thrown off by non-standard holding instructions. It's been fixed now and the new files are at the link.

![image](https://user-images.githubusercontent.com/9663827/120843218-c0af1300-c565-11eb-9549-88f0416f185e.png)

**Comment by aldobenitez** [comment]
Confirmed KSPI, KSGF, and KICT have no SID or STARs.
