### ISSUE TITLE
CZUL: SID/STAR update

### ISSUE THREAD

**Issue by aldobenitez** [ivao-xa/sectorfiles#39]
**Old information**
SID/STAR

**Sector**
CZUL

**Additional context**
Requested for: CYOW CYQB CYUL

**Comment by wessupermare** [comment]
https://1drv.ms/u/s!AmrBW1nfZNbRz_xrssD__TQIAaM2Vw?e=vck9n3

If someone could validate these for me and file the pull request, that would be much appreciated.

**Comment by wessupermare** [comment]
![image](https://user-images.githubusercontent.com/9663827/120843455-066bdb80-c566-11eb-83b1-19a8f872884f.png)

Same holding issue as #38. Updated.

**Comment by wessupermare** [comment]
Okay, I've updated them in the folder. Same link as before should still work. https://1drv.ms/u/s!AmrBW1nfZNbRz_xrssD__TQIAaM2Vw?e=vck9n3
