### ISSUE TITLE
KTPA New Taxiway layout

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#49]
**Old information**
Taxiways got added / removed

**Sector**
KZMA

**Current version**
AIRAC 2105
![image](https://user-images.githubusercontent.com/85259503/120891987-0e7e5680-c60c-11eb-81c3-e0beff1a148b.png)
--------------------------------------------------------------------------------------------------------------------
https://earth.google.com/web/search/ktpa+airport/@27.97659519,-82.53172787,6.66581413a,5339.03492252d,35y,0.00037761h,25.20408772t,-0r/data=CncaTRJHCiUweDg4YzJjMjQ2OTM5ZTQ0NDM6MHg3YTViODQwOGM2MDFkNTA5GTk14agm-jtAIQGqEyv-oVTAKgxrdHBhIGFpcnBvcnQYASABIiYKJAmlELFteTZCQBGmELFteTZCwBkekIj4OPgnQCEoDfuJMsVZwA

**Additional context**
-Taxiways need to be removed / 1 to be added
-Several renaming of taxiways (A&D&F etc.)

**Comment by wessupermare** [comment]
Hello! Are you planning on taking this one or do you want me to mark it as help wanted?

**Comment by MobiasTagill** [comment]
I don't really want to fuck around with Google earth. I could do the
taxiway relabeling tho

Wes Sleeman ***@***.***> schrieb am Sa., 5. Juni 2021, 3:18
PM:

**Comment by wessupermare** [comment]
Sounds good! I'll tag help wanted. Thanks!

**Comment by aldobenitez** [comment]
I can do those changes, thanks for pointing this out.

**Comment by wessupermare** [comment]
Assigned Aldo for the graphics & Toby for the labels.

**Comment by aldobenitez** [comment]
@MobiasTagill Highlighted outdated labels, probably
![tpa labels](https://user-images.githubusercontent.com/41238983/120900022-aa09ca00-c600-11eb-9cb5-4cd5dd14e086.png)
 best to redo the whole ktpa.txi file maybe?

**Comment by MobiasTagill** [comment]
Yeah i can update the taxi labels tonight! 👍🏻

Aldo Benitez ***@***.***> schrieb am Sa., 5. Juni 2021, 7:19
PM:
