### ISSUE TITLE
KMCF Completely twisted

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#58]
**Describe the bug**
The Airport is inverted?

**Sector**
KZMA

**Expectation**
A clear and concise description of what you expect it should be.

**Screenshots**
AURORA:
![image](https://user-images.githubusercontent.com/85259503/120907842-2e8e3400-c665-11eb-93f2-9ac59c128c9c.png)
Flightaware & Skyvector:
![image](https://user-images.githubusercontent.com/85259503/120907847-3e0d7d00-c665-11eb-95a0-356b46e9a410.png)

**Environment (please complete the following information):**
 - Aurora Version (e.g. 1.2.14b):

**Additional context**
I am CONFUSION!

**Comment by wessupermare** [comment]
Rotate 90° right…
