### ISSUE TITLE
KZMA: KLAL Cargo ramp missing 

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#59]
**Old information**
Missing Cargo Ramp (Probably new?)

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/120907893-cb50d180-c665-11eb-9e88-02ea885a19f3.png)
![image](https://user-images.githubusercontent.com/85259503/120907904-d9065700-c665-11eb-8573-1a8eb60ff961.png)

**Additional context**
Missing the Cargo ramp

**Comment by AlexSkeleton12** [comment]
I'll give it a fix...

**Comment by AlexSkeleton12** [comment]
Looks like Google Earth has out of date satellite data for this airport. I don't see the Cargo Ramp. Unfixable I guess.

**Comment by MobiasTagill** [comment]
Ehm, i just checked on Google. Lemme send you a Screenshot in a few minutes

AlexSkeleton12 ***@***.***> schrieb am So., 6. Juni 2021,
6:41 PM:

**Comment by MobiasTagill** [comment]
![Uploading image.png…]()

**Comment by AlexSkeleton12** [comment]
Hmm. I don't seem to have that on my Google Earth...

**Comment by MobiasTagill** [comment]
Sweet @JordanKirkby thanks!
