### ISSUE TITLE
KZMA: KSRQ label issue

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#61]
**Old information**
TERMINAL Buggy gates

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/120908259-97c37680-c668-11eb-8122-bbaf6b208b63.png)

**Additional context**
This looks weird and buggy, Terminal needs Gates

**Comment by aldobenitez** [comment]
@MobiasTagill Gate chart

![image](https://user-images.githubusercontent.com/41238983/120921515-0d900800-c692-11eb-8ac0-7793d7296fb6.png)

**Comment by MobiasTagill** [comment]
Appreciate it, will change it myself c:
