### ISSUE TITLE
KZMA: KAPF Bend taxiway

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#67]
**Old information**
Taxiway has a curve

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/120908683-f7238580-c66c-11eb-82ba-fd4124104e22.png)
![image](https://user-images.githubusercontent.com/85259503/120908685-fd196680-c66c-11eb-9960-eb8ad930936d.png)

**Additional context**
Its straight, could take some time to re do that lol

**Comment by JordanKirkby** [comment]
I will completely re-do this airport.  Lots wrong with it, taxiways on west end are completely different, the section mentioned in the issue is an easy fix, but I will re-do all taxiways to be current.

**Comment by MobiasTagill** [comment]
I updated the taxiway labels but the layout itself is wrong. Appreciate it
