### ISSUE TITLE
KZLA: Hawthorne Municipal (KHHR) taxiway labels needed.

### ISSUE THREAD

**Issue by AlexSkeleton12** [ivao-xa/sectorfiles#72]
**Is your feature request related to a problem? Please describe.**
Hawthorne Municipal taxiway labels needed.

**Sector**
KZLA

**Additional context**
Help needed.

**Comment by MobiasTagill** [comment]
@AlexSkeleton12 If you want you can add the buildings. Finished the lables. If you dont want to do it i could just simply create an issue report

**Comment by AlexSkeleton12** [comment]
I'm unable to do buildings unfortunately...
