### ISSUE TITLE
KZMA; KFXE Missing Terminal & Minor Taxiway Edits

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#84]
**Old information**
Terminal Missing, minor runway edits 

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/121058372-8db48b80-c7c0-11eb-980e-7e7c9c044414.png)
![image](https://user-images.githubusercontent.com/85259503/121058432-9b6a1100-c7c0-11eb-86a9-47a0cced3fa3.png)

**Additional context**
Use Google Maps Satelite View --> Google Earth outdated
https://www.google.de/maps/search/kfexe+airport/@26.1982576,-80.1762756,2075m/data=!3m1!1e3

**Comment by wessupermare** [comment]
Superseded by #91. Closing duplicate.
