### ISSUE TITLE
KZMA: KPMP Whole new airport layout needed

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#87]
**Old information**
Aaaaaa lot of Taxiways 

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/121074910-cbbbaa80-c7d4-11eb-81b9-37e5d6bf84c0.png)
![image](https://user-images.githubusercontent.com/85259503/121074935-d413e580-c7d4-11eb-83cf-281ce50b9838.png)

**Additional context**
@JordanKirkby DO IT!

**Comment by MobiasTagill** [comment]
I can do the taxiway labels ;=)

**Comment by wessupermare** [comment]
Superseded by #91. Closing duplicate.
