### ISSUE TITLE
KZMA: KSUA small Taxiway needs to be added / removed

### ISSUE THREAD

**Issue by MobiasTagill** [ivao-xa/sectorfiles#90]
**Old information**
1 small taxiway needed and one more to be deleted

**Sector**
KZMA

**Current version**
![image](https://user-images.githubusercontent.com/85259503/121081357-e85be080-c7dc-11eb-8e36-1e8d84b23db3.png)

**Additional context**
Beginner friendly, fast :)

**Comment by wessupermare** [comment]
Superseded by #91. Closing duplicate.
