### ISSUE TITLE
KZMA - Blanket Graphics Issues - All graphical enhancements to be posted in here

### ISSUE THREAD

**Issue by JordanKirkby** [ivao-xa/sectorfiles#91]
Please comment below on any graphical issues that need to be resolved.  Try to keep your request pointed and with a screenshot of what needs to be changed.  Only 1 request per comment to keep this clean and simple to follow.  Once I have resolved the issue, I will edit your comment to say "completed" at the end.

I will comment once readied with a graphic of the fixed request.

**Comment by wessupermare** [comment]
↑ Just cleaned up the duplicates. :) ↑

**Comment by MobiasTagill** [comment]
KPGD Got fixed already by you @JordanKirkby
